######################################################################
# Automatically generated by qmake (3.1) Wed Sep 9 19:08:52 2020
######################################################################

TEMPLATE = app
TARGET = vulkan_test
INCLUDEPATH += . ./src

QT += core widgets gui concurrent
CONFIG += debug
CONFIG += c++17

OBJECTS_DIR = generated_files
MOC_DIR = generated_files

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS +=  src/VulkanFunctions.hpp \
			src/VulkanWindow.hpp \
			src/VulkanRenderer.hpp \
			src/Shader.hpp \
			src/Image.hpp \
			src/Buffer.hpp \
			src/Vertex.hpp \
			src/settings/ControlPanel.hpp

SOURCES +=  src/main.cpp \
			src/VulkanFunctions.cpp \
			src/VulkanWindow.cpp \
			src/VulkanRenderer.cpp \
			src/Shader.cpp \
			src/Image.cpp \
			src/Buffer.cpp \
			src/Vertex.cpp \
			src/settings/ControlPanel.cpp
